openapi: 3.1.0
info:
  title: SSE Example API
  version: 1.0.0
  description: An example API that provides server-sent events (SSE) for real-time data streaming.
servers:
  - url: https://api.example.com
    description: Production Server
  - url: http://localhost:3001
    description: Local Development Server
paths:
  /events:
    get:
      summary: Subscribe to Server-Sent Events
      description: Streams real-time events to the client using Server-Sent Events (SSE).
      operationId: getSSEEvents
      responses:
        "200":
          description: Stream of server-sent events.
          content:
            text/event-stream:
              schema:
                type: object
                properties:
                  event:
                    type: string
                    description: The type of the event.
                  data:
                    type: string
                    description: Payload of the event.
                  id:
                    type: string
                    description: Unique ID for the event.
                example:
                  event: message
                  id: "1"
                  data: Hello, World!
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Bearer authentication using a token.
security:
  - bearerAuth: []
